### ISSUE TITLE
Keras Parser and Supported Keras Versions

### ISSUE THREAD

**Issue by wschin** [onnx/onnxmltools#37]
For both of Sequential and Model, Keras parser works correctly with Keras 2.0.9 on Windows Anaconda3 locally. However, when running CI it failed with the following message.

tests/end2end/test_single_operator_with_cntk_backend.py:92: in _test_one_to_one_operator_core
    onnx_model = onnxmltools.convert_keras(keras_model)
onnxmltools/convert/main.py:31: in convert_keras
    return convert(model, name, initial_types=initial_types, doc_string=doc_string)
onnxmltools/convert/keras/convert.py:30: in convert
    topology = parse_keras(model, initial_types)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
model = <keras.models.Sequential object at 0x7f7b40cf4908>, initial_types = None
    def parse_keras(model, initial_types=None):
        raw_model_container = KerasModelContainer(model)
        topology = Topology(raw_model_container, default_batch_size=1, initial_types=initial_types)
        scope = topology.declare_scope('__root__')
          for node in model.inbound_nodes:
E       AttributeError: 'Sequential' object has no attribute 'inbound_nodes'
onnxmltools/convert/keras/_parse.py:74: AttributeError

**Comment by wschin** [comment]
As a temporal solution, we set keras version to 2.0.9 in CI in this [PR](https://github.com/onnx/onnxmltools/pull/36).
